apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: k8s-multi-herewardmills-com
spec:
  secretName: k8s-multi-herewardmills-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: k8s-multi.herewardmills.com
  dnsNames:
    - k8s-multi.herewardmills.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - k8s-multi.herewardmills.com
